name: 🚀 Backend Patch

on:
  schedule:
    - cron: '0 12 1-31/2 * *' # Alternate days at 12 PM (opposite pattern)
  workflow_dispatch:

jobs:
  backend-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update backend logic
        run: |
          echo "// patch: $(date)" >> utils/helpers.js
          echo "- $(date): Refined AI prompt input" >> openai-playground/prompt-notes.md
          echo "// rule change: $(date)" >> firebase-tests/firestore.rules

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(core): backend logic refinements"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PATH }}
