name: 🔄 Auto Commit to Main Branch

on:
  schedule:
    - cron: '0 7 * * *' # Runs daily at 7 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update meaningful files
        run: |
          echo "- Daily note: Auto-update on $(date)" >> openai-playground/prompt-notes.md
          echo "// auto update: $(date)" >> utils/helpers.js
          echo "// activity updated: $(date)" >> activity-log.js

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: automated daily update to logs and helpers" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PATH }}
