name: 🔄 Auto Commit Using GITHUB_TOKEN

on:
  schedule:
    - cron: '0 7 * * *' # Runs daily at 7 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create or update file
        run: |
          echo "// Updated at $(date)" >> activity-log.js

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: daily auto-commit" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PATH }}
