name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "muhammadammar28"
          git config --global user.email "ammarsattar85@gmail.com"

      - name: Make a dummy update
        run: |
          echo "// update on $(date)" >> daily.js

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "chore: auto-update"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main
